/*
 * TIMER1_TYPES.h
 *
 *  Created on: Feb 25, 2023
 *      Author: joseph
 */

#ifndef TIMER1_TIMER1_TYPES_H_
#define TIMER1_TIMER1_TYPES_H_

typedef enum
{
	TIMER1_NORMAL_MODE = 0,
	TIMER1_PHASE_CORRECT_PWM_8BIT_MODE,
	TIMER1_PHASE_CORRECT_PWM_9BIT_MODE,
	TIMER1_PHASE_CORRECT_PWM_10BIT_MODE,
	TIMER1_CTC_MODE,
	TIMER1_FASTPWM_8BIT_MODE,
	TIMER1_FASTPWM_9BIT_MODE,
	TIMER1_FASTPWM_10BIT_MODE,
	TIMER1_PHASE_FREQUENCY_PWM1_MODE,
	TIMER1_PHASE_FREQUENCY_PWM2_MODE,
	//and so on..

}Timer1_Mode;

typedef enum
{
	OC1_DISCONNECTED = 0,
	OC1_TOGGLE,
	//OC1_CLEAR,
	//OC1_SET,
	OC1_CLEAR_ON_COMPARE,
	OC1_SET_ON_COMPARE,
	//OC1_CLEAR_ON_COMPARE_COUNTING_UP_SET_ON_COMPARE_COUNTING_DOWN,
	//OC1_SET_ON_COMPARE_COUNTING_UP_CLEAR_ON_COMPARE_COUNTING_DOWN,
}Timer_OC1_Mode;

typedef enum
{
	ICU_NO_USE = 0,
	ICU_FALLING_EDGE_MODE = 1,
	ICU_RISING_EDGE_MODE = 2,
	ICU_RISING_FALLING_RF_MODE = 3,
	ICU_RISING_FALLING_FF_MODE = 4,
}Timer1_ICU_Edge_Mode;

typedef enum
{
	TIMER1_STOPPED = 0,
	TIMER1_CLK,
	TIMER1_CLK_DIV_8 = 8,
	TIMER1_CLK_DIV_64 = 64,
	TIMER1_CLK_DIV_256 = 256,
	TIMER1_CLK_DIV_1024 = 1024,
	TIMER1_EXTERNAL_FALLING_EDGE = 10,
	TIMER1_EXTERNAL_RISING_EDGE = 11

}Timer1_Frequency_PreScaler;

typedef enum
{
	TIMER1_OUT_OF_RANGE_VALUE = 0,
	TIMER1_MODE_ERROR = 0,
	TIMER1_INTERRUPT_MODE_ERROR = 0,
	TIMER1_OC1_MODE_ERROR,
	TIMER1_NULL_POINTER,
	TIMER1_NO_ERROR
}TIMER1_Error_Status;

typedef enum
{//Mask style
	TIMER1_INTERRUPT_OVERFLOW = 0b100,
	TIMER1_INTERRUPT_COMPARE_MATCH_B = 0b1000,
	TIMER1_INTERRUPT_COMPARE_MATCH_A = 0b10000,
	TIMER1_INTERRUPT_INPUT_CAPTURE =  0b100000,


}Timer1_INTERRUPT_ID;

#endif /* TIMER1_TIMER1_TYPES_H_ */
