/*
 * TIMER0_TYPES.h
 *
 *  Created on: Feb 24, 2023
 *      Author: joseph
 */

#ifndef TIMER0_TIMER0_TYPES_H_
#define TIMER0_TIMER0_TYPES_H_

typedef enum
{
	TIMER0_OUT_OF_RANGE_VALUE = 0,
	TIMER0_MODE_ERROR = 0,
	TIMER0_INTERRUPT_ERROR = 0,
	TIMER0_OC0_MODE_ERROR,
	TIMER0_NULL_POINTER,
	TIMER0_NO_ERROR
}TIMER0_Error_Status;

typedef enum
{
	TIMER0_DELAY_BUSY = 0,
	TIMER0_DELAY_NO_ERROR
}TIMER0_Delay_Status;

typedef enum
{
	TIMER0_NORMAL_MODE = 9,
	TIMER0_PWM_MODE,
	TIMER0_CTC_MODE,
	TIMER0_FASTPWM_MODE
}Timer0_Mode;

typedef enum
{
	OC0_DISCONNECTED =13,
	OC0_TOGGLE,
	OC0_CLEAR,
	OC0_SET,
	OC0_CLEAR_ON_COMPARE_SET_AT_TOP,
	OC0_SET_ON_COMPARE_CLEAR_AT_TOP,
	OC0_CLEAR_ON_COMPARE_COUNTING_UP_SET_ON_COMPARE_COUNTING_DOWN,
	OC0_SET_ON_COMPARE_COUNTING_UP_CLEAR_ON_COMPARE_COUNTING_DOWN,
}Timer_OC0_Mode;

typedef enum
{
	TIMER0_STOPPED = 0,
	TIMER0_CLK,
	TIMER0_CLK_DIV_8 = 8,
	TIMER0_CLK_DIV_64 = 64,
	TIMER0_CLK_DIV_256 = 256,
	TIMER0_CLK_DIV_1024 = 1024,
	TIMER0_EXTERNAL_FALLING_EDGE = 10,
	TIMER0_EXTERNAL_RISING_EDGE = 11

}Timer0_Frequency_PreScaler;

typedef enum
{
	TIMER0_INTERRUPT_OVERFLOW = 9,
	TIMER0_INTERRUPT_COMPARE_MATCH,
}Timer0_INTERRUPT_ID;


#endif /* TIMER0_TIMER0_TYPES_H_ */
